name: 'Install Linux Dependencies'
description: 'Installs Ubuntu GTK and Python Dependencies'
runs:
  using: composite
  steps:
    - run: >
        sudo apt-get update -qq && sudo apt-get install -qq --no-install-recommends
        gir1.2-gtk-3.0 libgirepository1.0-dev libgtksourceview-4-dev upx
      shell: bash
